# Generated by Django 4.2.4 on 2023-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcionline',
            name='descri_etp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dcionline',
            name='objetivo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dcionline',
            name='tipoEtp',
            field=models.CharField(default='', max_length=150),
        ),
    ]
