# Generated by Django 4.2.4 on 2023-08-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0002_dcionline_descri_etp_dcionline_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcionline',
            name='lista_teste',
            field=models.TextField(default=''),
        ),
    ]
