# Generated by Django 4.2.4 on 2023-08-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0004_oesdci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcionline',
            name='lista_teste',
        ),
    ]
