# Generated by Django 4.2.4 on 2023-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0005_remove_dcionline_lista_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='oesdci',
            name='etp_vinculada',
            field=models.CharField(default='', max_length=100),
        ),
    ]
