# Generated by Django 4.2.4 on 2023-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0006_oesdci_etp_vinculada'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtsDCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ots_id', models.CharField(max_length=100)),
                ('num_ots', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=100)),
                ('proprietario', models.CharField(max_length=100)),
            ],
        ),
    ]
