# Generated by Django 4.2.4 on 2023-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0007_otsdci'),
    ]

    operations = [
        migrations.AddField(
            model_name='otsdci',
            name='etp_vinculada',
            field=models.CharField(default='', max_length=100),
        ),
    ]
