# Generated by Django 4.2.4 on 2023-08-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0008_otsdci_etp_vinculada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otsdci',
            name='proprietario',
        ),
    ]
