# Generated by Django 4.2.4 on 2023-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0011_remove_otsdci_num_ots_remove_otsdci_ots_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otsdci',
            name='num_ots',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='otsdci',
            name='ots_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='otsdci',
            name='sigla',
            field=models.CharField(default='', max_length=100),
        ),
    ]
