# Generated by Django 4.2.4 on 2023-08-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0012_otsdci_num_ots_otsdci_ots_id_otsdci_sigla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtsDCI',
        ),
    ]
