# Generated by Django 4.2.4 on 2023-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0014_otsdci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otsdci',
            name='proprietario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
