# Generated by Django 4.2.4 on 2023-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0015_alter_otsdci_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='oesdci',
            name='oe_selec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otsdci',
            name='ots_selec',
            field=models.BooleanField(default=False),
        ),
    ]
