# Generated by Django 4.2.4 on 2023-08-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0016_oesdci_oe_selec_otsdci_ots_selec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DciOnline',
            new_name='EtpOnline',
        ),
    ]
