# Generated by Django 4.2.4 on 2023-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0017_rename_dcionline_etponline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DciGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etp_value', models.CharField(max_length=100)),
                ('list_oes', models.TextField()),
                ('list_ots', models.TextField()),
                ('obv_atr', models.TextField()),
                ('obv_oes', models.TextField()),
                ('obv_rede_ext', models.TextField()),
                ('topologia', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('obv_final', models.TextField()),
                ('tipo_entrega', models.CharField(choices=[('TOTAL', 'Total'), ('PARCIAL', ' Parcial'), ('PARCIAL FINAL', 'Parcial Final')], default='', max_length=150)),
            ],
        ),
    ]
