# Generated by Django 4.2.4 on 2023-08-14 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0018_dcigerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcigerada',
            name='hora_geracao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
