# Generated by Django 4.2.4 on 2023-08-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0019_dcigerada_hora_geracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcigerada',
            name='link',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dcigerada',
            name='obv_atr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dcigerada',
            name='obv_final',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dcigerada',
            name='obv_oes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dcigerada',
            name='obv_rede_ext',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dcigerada',
            name='topologia',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
