# Generated by Django 4.2.4 on 2023-08-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0021_otsdci_teste_alter_dcigerada_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otsdci',
            name='teste',
        ),
    ]
